
timezones = {'Indiana': 'US/Eastern', 
             'Florida': 'US/Eastern',
             'Delaware': 'US/Eastern',
             'Rhode Island': 'US/Eastern',
             'Connecticut': 'US/Eastern',
             'Pennsylvania': 'US/Eastern',
             'Oklahoma': 'US/Central',
             'New York': 'US/Eastern',
             'Ohio': 'US/Eastern',
             'New Jersey': 'US/Eastern',
             'Nevada': 'US/Pacific',
             'Wyoming': 'US/Mountain',
             'Nebraska': 'US/Central',
             'West Virginia': 'US/Eastern',
             'North Dakota': 'US/Central',
             'Kansas': 'US/Central',
             'South Carolina': 'US/Eastern',
             'Alaska': 'US/Alaska',
             'North Carolina': 'US/Eastern',
             'Georgia': 'US/Eastern',
             'Alabama': 'US/Central',
             'Arizona': 'US/Mountain',
             'Virginia': 'US/Eastern',
             'Maine': 'US/Eastern',
             'New Hampshire': 'US/Eastern',
             'Illinois': 'US/Central',
             'Montana': 'US/Mountain',
             'Massachusetts': 'US/Eastern',
             'South Dakota': 'US/Central',
             'Mississippi': 'US/Central',
             'Missouri': 'US/Central',
             'New Mexico': 'US/Mountain',
             'California': 'US/Pacific',
             'Michigan': 'US/Eastern',
             'Wisconsin': 'US/Central',
             'Vermont': 'US/Eastern',
             'Oregon': 'US/Pacific',
             'Louisiana': 'US/Central',
             'Hawaii': 'Pacific/Honolulu',
             'Washington': 'US/Pacific',
             'Idaho': 'US/Mountain',
             'Utah': 'US/Mountain',
             'Colorado': 'US/Mountain',
             'Minnesota': 'US/Central',
             'Texas': 'US/Central',
             'Arkansas': 'US/Central',
             'Kentucky': 'US/Eastern',
             'Maryland': 'US/Eastern',
             'Tennessee': 'US/Central',
             'Iowa': 'US/Central'}

